---
version: "3.8"

services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  sonarqube:
    build:
      context: .
      dockerfile: sonarqube.Dockerfile
    # Must set web.context when behind reverse proxy:
    # https://github.com/SonarSource/docker-sonarqube/issues/17#issuecomment-312049277
    command: -Dsonar.web.context=/sonar
    depends_on:
      - postgres
    ports:
      - 9000:9000
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - conf:/opt/sonarqube/conf
      - data:/opt/sonarqube/data
      - logs:/opt/sonarqube/logs
      - extensions:/opt/sonarqube/extensions
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    depends_on:
      - sonarqube
    ports:
      - 80:80

volumes:
  conf:
  data:
  logs:
  extensions:
  postgresql:
  postgresql_data:
